"""initial schema

Revision ID: 7ab3a4dcb760
Revises: 
Create Date: 2026-09-25 13:12:03.586097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab3a4dcb760'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_email', sa.String(), nullable=False),
    sa.Column('target_email', sa.String(), nullable=False),
    sa.Column('old_role', sa.String(), nullable=False),
    sa.Column('new_role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit'))
    )
    op.create_table('delegates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), server_default='', nullable=False),
    sa.Column('dateofbirth', sa.String(), server_default='', nullable=False),
    sa.Column('gender', sa.String(), server_default='', nullable=False),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delegates')),
    sa.UniqueConstraint('email', name=op.f('uq_delegates_email'))
    )
    op.create_table('mm_delegates',
    sa.Column('delegate_id', sa.String(), nullable=False),
    sa.Column('country', sa.String(), server_default='', nullable=False),
    sa.Column('committee', sa.String(), server_default='', nullable=False),
    sa.Column('d1_bf', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('d1_lunch', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('d1_hitea', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('d2_bf', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('d2_lunch', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('d2_hitea', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('d3_bf', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('d3_lunch', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('d3_hitea', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delegate_id'], ['delegates.id'], name=op.f('fk_mm_delegates_delegate_id_delegates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('delegate_id', name=op.f('pk_mm_delegates'))
    )
    op.create_table('mun_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegate_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('committee', sa.String(), server_default='', nullable=False),
    sa.Column('delegation', sa.String(), server_default='', nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('award', sa.String(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['delegate_id'], ['delegates.id'], name=op.f('fk_mun_experiences_delegate_id_delegates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mun_experiences'))
    )
    op.create_index(op.f('ix_mun_experiences_delegate_id'), 'mun_experiences', ['delegate_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='delegate', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('delegate', 'oc', 'admin')", name=op.f('ck_users_role_valid')),
    sa.ForeignKeyConstraint(['email'], ['delegates.email'], name=op.f('fk_users_email_delegates'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email', name=op.f('pk_users'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_mun_experiences_delegate_id'), table_name='mun_experiences')
    op.drop_table('mun_experiences')
    op.drop_table('mm_delegates')
    op.drop_table('delegates')
    op.drop_table('admin_audit')
    # ### end Alembic commands ###
